[package]
name = "specs-derive"
version = "0.4.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "Custom derive macro for Specs components"
documentation = "https://docs.rs/specs-derive"
repository = "https://github.com/slide-rs/specs/tree/master/specs-derive"
keywords = ["gamedev", "parallel", "specs", "ecs", "derive"]
license = "MIT/Apache-2.0"

[dependencies]
proc-macro2 = "0.4"
syn = "0.15"
quote = "0.6"

[lib]
proc-macro = true
