[package]
name = "custom_component_macro"
version = "0.1.0"
authors = ["DefecateRainbows <cedhut02@gmail.com>"]
edition = "2018"

[dependencies]
mopa = "0.2.2"
typetag = "0.1.1"
imgui = "0.0.22"
specs = { path = "../specs/" }
